acl blacklist dstdomain "/etc/squid/blacksites"
acl whitelist dstdomain "/etc/squid/whitesites"
acl whitelist_ips src "/etc/squid/whiteips"
acl blacklist_ips src "/etc/squid/blackips"
acl class_mon_thu_fri time MTWHF 08:35-15:10
acl class_tue_wed time TWH 08:35-16:10
acl class_sat time A 08:35-12:30
# temporary: deny all time M 00:00-24:00
acl class_mon_all time M 00:00-24:00
acl class_time any-of class_mon_all class_mon_thu_fri class_tue_wed class_sat
http_access allow whitelist
http_access allow whitelist_ips
deny_info ERR_ACCESS_DENIED blacklist blacklist_ips
http_access deny blacklist class_time
http_access deny blacklist_ips class_time
http_upgrade_request_protocols WebSocket allow whitelist
http_upgrade_request_protocols WebSocket allow whitelist_ips
ssl_bump splice whitelist
ssl_bump splice whitelist_ips
error_directory /etc/squid
