acl blacklist dstdomain "/etc/squid/blacksites"
acl whitelist dstdomain "/etc/squid/whitesites"
acl whitelist_ips src "/etc/squid/whiteips"
acl blacklist_ips src "/etc/squid/blackips"
acl class_1st      time MTWHF 08:35-09:25
acl break_1st      time MTWHF 09:25-09:35
acl class_2nd      time MTWHF 09:35-10:25
acl break_2nd      time MTWHF 10:25-10:40
acl class_3rd      time MTWHF 10:40-11:30
acl break_3rd      time MTWHF 11:30-11:40
acl class_4th      time MTWHF 11:40-12:30
acl lunch_break    time MTWHF 12:30-13:20
acl class_5th      time MTWHF 13:20-14:10
acl break_5th      time MTWHF 14:10-14:20
acl class_6th      time MTWHF 14:20-15:10
acl break_6th      time TW 15:10-15:20
acl class_7th      time TW 15:20-16:10
acl sat_class_1st  time A 08:35-09:25
acl sat_break_1st  time A 09:25-09:35
acl sat_class_2nd  time A 09:35-10:25
acl sat_break_2nd  time A 10:25-10:40
acl sat_class_3rd  time A 10:40-11:30
acl sat_break_3rd  time A 11:30-11:40
acl sat_class_4th  time A 11:40-12:30
acl class_time any-of \
    class_1st class_2nd class_3rd class_4th class_5th class_6th class_7th \
    sat_class_1st sat_class_2nd sat_class_3rd sat_class_4th
http_access allow whitelist
http_access allow whitelist_ips
deny_info ERR_ACCESS_DENIED blacklist blacklist_ips
http_access deny blacklist class_time
http_access deny blacklist_ips class_time
http_upgrade_request_protocols WebSocket allow whitelist
http_upgrade_request_protocols WebSocket allow whitelist_ips
ssl_bump splice whitelist
ssl_bump splice whitelist_ips
error_directory /etc/squid
